input_variables: bkg_morphing_boosted_dnn_input_variables

preprocess_variables_functions:
  {
  }

signal_sample: [DATA_JetMET_JMENano_E_boosted_skimmed,DATA_JetMET_JMENano_F_boosted_skimmed,DATA_JetMET_JMENano_G_boosted_skimmed,TTto2L2Nu_skimmed,TTtoLNu2Q_skimmed,TTto4Q_skimmed]
background_sample: [DATA_JetMET_JMENano_E_boosted_skimmed,DATA_JetMET_JMENano_F_boosted_skimmed,DATA_JetMET_JMENano_G_boosted_skimmed,TTto2L2Nu_skimmed,TTtoLNu2Q_skimmed,TTto4Q_skimmed]

run2: False
signal_region: [boosted_qcd_B_region]
background_region: [boosted_qcd_A_region]
signal_dataset: [DATA_JetMET_JMENano_E_2022_postEE_EraE,DATA_JetMET_JMENano_F_2022_postEE_EraF,DATA_JetMET_JMENano_G_2022_postEE_EraG,TTto2L2Nu_2022_postEE,TTtoLNu2Q_2022_postEE,TTto4Q_2022_postEE]
background_dataset: [DATA_JetMET_JMENano_E_2022_postEE_EraE,DATA_JetMET_JMENano_F_2022_postEE_EraF,DATA_JetMET_JMENano_G_2022_postEE_EraG,TTto2L2Nu_2022_postEE,TTtoLNu2Q_2022_postEE,TTto4Q_2022_postEE]
oversample_split: True
undersample: True

multiclass: True

ML_model: DNN_multiclass_model

data_format: coffea

batch_size: 1024
epochs: 50

learning_rate: 3e-4
learning_rate_schedule: e20_drop75

early_stopping: True
patience: 5
min_delta: 1e-5

eval_param: "acc"

train_fraction: 0.7125
val_fraction: 0.2375
test_fraction: 0.05

class_weights: [1000.0, 500, 1000, 500]

data_dirs: [/work/bevila_t/PostDoc/HH4b/Output/PocketCoffea/test_fatjets_training_et_ttbar/]
